
USE coffeeshop;

create TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
login VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
phone VARCHAR(50) NOT NULL UNIQUE,
role TINYINT NOT NULL
);

create TABLE IF NOT EXISTS address(
user_id INTEGER, FOREIGN KEY (user_id) REFERENCES users(id),
street VARCHAR(50) NOT NULL,
house INTEGER NOT NULL,
flat INTEGER
);

create TABLE IF NOT EXISTS orders(
id INTEGER PRIMARY KEY AUTO_INCREMENT,
user_id INTEGER, FOREIGN KEY(user_id) REFERENCES users(id),
date varchar(50) NOT NULL
);

create TABLE IF NOT EXISTS items(
id INTEGER PRIMARY KEY AUTO_INCREMENT,
order_id INTEGER, FOREIGN KEY(order_id) REFERENCES orders(id),
name VARCHAR(100) NOT NULL,
weight DECIMAL NOT NULL,
cost DECIMAL NOT NULL
);











